language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
notifications:
  email: false
  irc:
    skip_join: false
    on_success: always
    on_failure: always
    channels:
      - "irc.rizon.net#/g/spam"
    template:
      - "%{repository}#%{build_number} (%{commit} by %{author}): %{message}"
      - "Build details: %{build_url}"
